sudo: false

language: node_js

node_js:
  - "stable"

services:
  - postgresql

notifications:
  email: false

install:
  - npm install

before_script:
  - psql -c 'create database teamwork;' -U postgres

script:
   -npm run coverage

global:
  - CODECLIMATE_REPO_TOKEN=fd70a624fd831f005700c4036e05d1bf00d316c798e22af7af0d5ac699614083
 